# Generated by Django 5.0.4 on 2024-07-17 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authgym', '0002_enrollment_selectmembershipplan_trainer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SelectMemberShipplan',
            new_name='Membershipplan',
        ),
    ]
