# Generated by Django 5.0.4 on 2024-07-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authgym', '0004_enrollment_duedate_enrollment_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='gallery')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
