# Generated by Django 5.0.4 on 2024-07-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authgym', '0006_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='PhoneNumber',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
